"""
Export a drafted scoping review to a single Markdown file.

Usage:
    python tests/export_review.py <project_id>            # writes to outputs/<project_id>.md
    python tests/export_review.py <project_id> output.md  # writes to specified path

Project IDs are 12-character hex strings (e.g. 'a81c0f8fc8a7') and can be
seen at the start of any smoke test run, or by listing data/processed/.
"""

import json
import sys
from pathlib import Path

# The canonical PRISMA-ScR section order for the assembled manuscript.
# This is NOT the dependency order — it's the order sections appear in
# the published article.
MANUSCRIPT_ORDER = [
    "title",
    "abstract",
    "introduction_rationale",
    "introduction_objectives",
    "methods_protocol",
    "methods_eligibility",
    "methods_information_sources",
    "methods_search",
    "methods_selection",
    "methods_data_charting",
    "methods_data_items",
    "methods_synthesis",
    "results_selection",
    "results_characteristics",
    "results_critical_appraisal",
    "results_individual_sources",
    "results_synthesis",
    "discussion_summary",
    "discussion_limitations",
    "discussion_conclusions",
    "funding",
]

# Human-readable section headings for the assembled manuscript.
SECTION_HEADINGS = {
    "title": None,  # title is rendered as the H1 itself
    "abstract": "Abstract",
    "introduction_rationale": "1. Introduction",
    "introduction_objectives": "1.1 Objectives",
    "methods_protocol": "2. Methods",
    "methods_eligibility": "2.1 Eligibility criteria",
    "methods_information_sources": "2.2 Information sources",
    "methods_search": "2.3 Search strategy",
    "methods_selection": "2.4 Selection of sources",
    "methods_data_charting": "2.5 Data charting",
    "methods_data_items": "2.6 Data items",
    "methods_synthesis": "2.7 Synthesis of results",
    "results_selection": "3. Results",
    "results_characteristics": "3.1 Characteristics of included sources",
    "results_critical_appraisal": "3.2 Critical appraisal",
    "results_individual_sources": "3.3 Individual sources of evidence",
    "results_synthesis": "3.4 Synthesis of findings",
    "discussion_summary": "4. Discussion",
    "discussion_limitations": "4.1 Limitations",
    "discussion_conclusions": "4.2 Conclusions",
    "funding": "5. Funding and conflicts of interest",
}


def export(project_id: str, output_path: Path | None = None) -> Path:
    project_file = Path("data/processed") / project_id / "project.json"
    if not project_file.exists():
        raise FileNotFoundError(
            f"Project file not found: {project_file}. "
            f"Run a smoke test first, or check the project_id."
        )

    data = json.loads(project_file.read_text())
    sections = data.get("sections", {})

    if output_path is None:
        output_dir = Path("data/exports")
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"{project_id}.md"
    else:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []

    # Project metadata header
    lines.append("<!-- AUTO-GENERATED by DentEd-ScopingReviewer -->\n")
    lines.append(f"<!-- Project ID: {project_id} -->\n")
    lines.append(f"<!-- Mode: {data.get('mode')} -->\n")
    lines.append(f"<!-- Generated: {data.get('updated_at')} -->\n\n")

    # Title goes first as the H1
    title_section = sections.get("title", {})
    if title_section.get("draft"):
        title_text = title_section["draft"].strip().strip("#").strip()
        lines.append(f"# {title_text}\n\n")

    # All other sections in manuscript order
    drafted_count = 0
    blocked_count = 0
    pending_count = 0
    for section_id in MANUSCRIPT_ORDER:
        if section_id == "title":
            continue

        section = sections.get(section_id, {})
        draft = section.get("draft")
        status = section.get("status", "pending")
        heading = SECTION_HEADINGS.get(section_id, section_id)

        lines.append(f"## {heading}\n\n")

        if draft:
            drafted_count += 1
            lines.append(f"{draft.strip()}\n\n")

            # Include critique score if present
            critique = section.get("critique")
            if critique:
                verdict = critique.get("verdict", "")
                score = critique.get("overall_score", 0)
                marker = {
                    "approve": "✓ Approved",
                    "revise": "◯ Revision suggested",
                    "reject": "✗ Rejected",
                }.get(verdict, verdict)
                lines.append(
                    f"> _**Critique:** {marker} ({score}/100). "
                    f"Compliance {critique.get('compliance_score', 0)}, "
                    f"faithfulness {critique.get('faithfulness_score', 0)}, "
                    f"scope {critique.get('scope_score', 0)}, "
                    f"length {critique.get('length_score', 0)}._\n\n"
                )
        elif status == "blocked":
            blocked_count += 1
            missing = section.get("missing_evidence", [])
            lines.append(
                f"_[Section blocked — missing evidence: "
                f"{', '.join(missing)}]_\n\n"
            )
        else:
            pending_count += 1
            lines.append(f"_[Section status: {status}]_\n\n")

    # Footer summary
    total = len(MANUSCRIPT_ORDER) - 1  # excluding title
    lines.append("---\n\n")
    lines.append(f"**Generation summary:** {drafted_count}/{total} sections drafted")
    if blocked_count:
        lines.append(f", {blocked_count} blocked")
    if pending_count:
        lines.append(f", {pending_count} pending")
    lines.append(".\n")

    output_path.write_text("".join(lines))
    return output_path


def main():
    if len(sys.argv) < 2:
        print("Usage: python tests/export_review.py <project_id> [output_path]")
        # List available projects
        processed = Path("data/processed")
        if processed.exists():
            projects = sorted(p.name for p in processed.iterdir() if p.is_dir())
            if projects:
                print("\nAvailable project IDs:")
                for p in projects[-10:]:
                    print(f"  {p}")
        sys.exit(1)

    project_id = sys.argv[1]
    output_path = Path(sys.argv[2]) if len(sys.argv) > 2 else None
    written = export(project_id, output_path)
    print(f"✅ Manuscript exported to: {written}")


if __name__ == "__main__":
    main()
